[package]
name = "fluit"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
pixels = "0.6"
winit = "0.25"
winit_input_helper = "0.10"